package com.university.application.model.enums;

public enum Speciality {
    SOFTWARE_CONTROLLED_ELECTRON_OPTICAL_SYSTEMS,
    MODELING_AND_COMPUTER_DESIGN_OF_RADIO_ELECTRONIC_MEANS,
    DESIGN_AND_PRODUCTION_OF_SOFTWARE_CONTROLLED_ELECTRONIC_MEANS,

    INDUSTRIAL_ELECTRONICS,
    AUTOMATED_INFORMATION_PROCESSING_SYSTEMS,
    INFORMATION_TECHNOLOGIES_AND_MANAGEMENT_IN_TECHNICAL_SYSTEMS,

    RADIO_ENGINEERING,
    RADIO_ELECTRONIC_SYSTEMS_RADIOINFORMATICS,

    INFORMATION_TECHNOLOGY_SOFTWARE,
    COMPUTERS_SYSTEMS_AND_NETWORKS,
    ELECTRONIC_COMPUTING_TOOLS;
}
